name: dolphin-emulator-kyu
base: core24
version: '2512'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: GameCube / Wii / Triforce Emulator
description: |
  Dolphin is an emulator for two recent Nintendo video game consoles: the GameCube and the Wii. It allows PC gamers to enjoy games for these two consoles in full HD (1080p) with several enhancements: compatibility with all PC controllers, turbo speed, networked multiplayer, and even more!
grade: stable
confinement: strict
icon: dolphin-emu.svg

apps:
  dolphin-emulator-kyu:
    command-chain: [snap/command-chain/unset-qt_qpa_platform]
    command: usr/games/dolphin-emu
    desktop: usr/local/share/applications/dolphin-emu.desktop
    common-id: org.DolphinEmu.dolphin-emu
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2
      - hardware-observe
      - optical-drive
      - raw-usb
      - hidraw

plugs:
  shared-memory:
    private: true
  lxqt-support-core24:
    content: lxqt-support-core24
    interface: content
    target: $SNAP/lxqt-support
    default-provider: lxqt-support-core24

layout:
  /usr/share/games/dolphin-emu/sys:
    symlink: $SNAP/usr/share/games/dolphin-emu/sys
  /usr/share/games/locale:
    bind: $SNAP/usr/local/share/locale
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support/usr/share/Kvantum

parts:
  dolphin-emu-app:
    plugin: cmake
    source: https://github.com/dolphin-emu/dolphin.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - libbluetooth-dev
      - libasound2-dev
      - libgl1-mesa-dev
      - libcurl4-openssl-dev
      - libsdl2-dev
      - libevdev-dev
      - libfreetype-dev
      - libzstd-dev
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DENABLE_ALSA=ON
      - -DENABLE_SDL=ON
      - -DENABLE_EVDEV=ON
      - -DCMAKE_INSTALL_BINDIR=/usr/games
      - -DCMAKE_INSTALL_DATADIR=/usr/share/games
    override-build: |
      craftctl default
      sed -e 's|Name=Dolphin Emulator|Name=Dolphin Emulator [Kyu]|' -i  $CRAFT_PART_INSTALL/usr/local/share/applications/dolphin-emu.desktop

  dependencies:
    after: [command-chain]
    plugin: nil
    stage-packages:
      - libbluetooth3
      - libpugixml1v5
      - libasound2t64
      - libasound2-plugins
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libbluetooth.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpugixml.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjack.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib

  command-chain:
    after: [dolphin-emu-app]
    plugin: dump
    source: ./command-chain/
    organize:
      unset-qt_qpa_platform: snap/command-chain/unset-qt_qpa_platform
